#
# https://docs.portainer.io/
# LTS image: https://docs.portainer.io/whats-new#long-term-support-lts
# STS image: https://docs.portainer.io/sts/whats-new#short-term-support-sts
#
---
services:
#
  portainer:
    image: ${PORTAINER_IMAGE}
    container_name: portainer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
    restart: unless-stopped
#
networks:
  default:
    name: ${CONNET}
    external: true
